import json
from pathlib import Path
path = Path(r'C:/Users/Aaradhya/Downloads/_Organized/Fuse AI Fellowship/FUSE AIF 2026 M2/WK7/Week_7_Clustering_Assignment_executed.ipynb')
nb = json.loads(path.read_text(encoding='utf-8'))

# Fix malformed print formatting in customer feature construction cell
nb['cells'][9]['source'] = [
    "# ── Reference Date ──────────────────────────────────────────────────────────\n",
    "# Choose a reference date for Recency calculation\n",
    "# Justify your choice in a comment — why this date?\n",
    "reference_date = df_clean['InvoiceDate'].max() + pd.Timedelta(days=1)\n",
    "\n",
    "# ── Recency ──────────────────────────────────────────────────────────────────\n",
    "# Days since last purchase per customer\n",
    "recency = df_clean.groupby('Customer ID')['InvoiceDate'].max().reset_index()\n",
    "recency['Recency'] = (reference_date - recency['InvoiceDate']).dt.days\n",
    "\n",
    "# ── Frequency ────────────────────────────────────────────────────────────────\n",
    "# Number of unique invoices per customer\n",
    "frequency = df_clean.groupby('Customer ID')['Invoice'].nunique().reset_index(name='Frequency')\n",
    "\n",
    "# ── Monetary ─────────────────────────────────────────────────────────────────\n",
    "# Total spend per customer\n",
    "monetary = df_clean.groupby('Customer ID')['TotalPrice'].sum().reset_index(name='Monetary')\n",
    "\n",
    "# ── Combine into customer matrix ─────────────────────────────────────────────\n",
    "customer_df = recency[['Customer ID', 'Recency']].merge(frequency, on='Customer ID').merge(monetary, on='Customer ID')\n",
    "\n",
    "# Add extended features\n",
    "customer_df['AvgBasketSize'] = customer_df['Monetary'] / customer_df['Frequency']\n",
    "# AvgBasketSize measures the average spend per purchase event. It helps identify customers who may make\n",
    "# fewer, larger purchases versus those buying more frequently in smaller baskets.\n",
    "# It can be skewed by one-off high-ticket orders, so it should be interpreted alongside Frequency.\n",
    "unique_products = df_clean.groupby('Customer ID')['StockCode'].nunique().reset_index(name='UniqueProducts')\n",
    "customer_df = customer_df.merge(unique_products, on='Customer ID', how='left')\n",
    "# UniqueProducts measures purchase breadth and engagement across the catalog.\n",
    "# Customers with high Monetary but low UniqueProducts may be loyal to a few categories,\n",
    "# while high UniqueProducts implies exploration and diverse product interest.\n",
    "\n",
    "invoice_gaps = (\n",
    "    df_clean.sort_values(['Customer ID', 'InvoiceDate'])\n",
    "    .groupby('Customer ID')['InvoiceDate']\n",
    "    .apply(lambda x: x.diff().dt.days.dropna().mean())\n",
    "    .reset_index(name='AvgDaysBetween')\n",
    ")\n",
    "customer_df = customer_df.merge(invoice_gaps, on='Customer ID', how='left')\n",
    "customer_df['AvgDaysBetween'] = customer_df['AvgDaysBetween'].fillna(customer_df['Recency'])\n",
    "# AvgDaysBetween captures purchase cadence. For one-time buyers, we fill with Recency so their\n",
    "# inactivity is still reflected in the feature.\n",
    "\n",
    "customer_df.head()\n",
    "\n",
    "# Sanity check\n",
    "print(\"These numbers should match.\")\n",
    "print(f\"Customer matrix shape: {customer_df.shape}\")\n",
    "print(f\"Unique customers in clean data: {df_clean['Customer ID'].nunique()}\")\n",
]

# Fix malformed hierarchical dendrogram cell
nb['cells'][19]['source'] = [
    "# ── Step 1: Plot Dendrogram ──────────────────────────────────────────────────\n",
    "# Use a sample of your data for the dendrogram (full data will be too slow)\n",
    "# Justify your sample size in a comment\n",
    "\n",
    "SAMPLE_SIZE = 300  # adjust if needed\n",
    "sample_idx = np.random.choice(len(X_scaled), SAMPLE_SIZE, replace=False)\n",
    "X_sample = X_scaled[sample_idx]\n",
    "\n",
    "# Compute linkage matrix for Ward linkage\n",
    "Z = linkage(X_sample, method='ward')\n",
    "\n",
    "# Plot Ward dendrogram\n",
    "plt.figure(figsize=(16, 6))\n",
    "dendrogram(Z, truncate_mode='lastp', p=30, leaf_rotation=90., leaf_font_size=10.)\n",
    "plt.title('Hierarchical Clustering Dendrogram (Ward Linkage)')\n",
    "plt.xlabel('Sample Index')\n",
    "plt.ylabel('Distance')\n",
    "plt.show()\n",
    "\n",
    "# The dendrogram should show a natural jump in merge distance near the final merges.\n",
    "# A large vertical gap in the final clusters suggests a reasonable cut point.\n",
    "last_heights = Z[:, 2]\n",
    "\n",
    "print('Ward linkage top merge heights:', last_heights[-10:])\n",
    "print('Ward linkage largest final jump:', np.max(np.diff(last_heights[-10:])))\n",
    "# We look for a cut on the dendrogram where the merge distance jumps sharply, indicating fewer, well-separated clusters.\n",
    "\n",
    "# Compare with average linkage to ensure the chosen cut is not linkage-specific.\n",
    "Z_avg = linkage(X_sample, method='average')\n",
    "avg_last_heights = Z_avg[:, 2]\n",
    "print('Average linkage top merge heights:', avg_last_heights[-10:])\n",
    "print('Average linkage largest final jump:', np.max(np.diff(avg_last_heights[-10:])))\n",
    "\n",
    "plt.figure(figsize=(16, 6))\n",
    "dendrogram(Z_avg, truncate_mode='lastp', p=30, leaf_rotation=90., leaf_font_size=10.)\n",
    "plt.title('Hierarchical Clustering Dendrogram (Average Linkage)')\n",
    "plt.xlabel('Sample Index')\n",
    "plt.ylabel('Distance')\n",
    "plt.show()\n",
]

path.write_text(json.dumps(nb, indent=1), encoding='utf-8')
print('Notebook patched.')
